### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by listenLearning** [chengqiangboy/spark-alluxio-blockstore#1]
不好意思，就是我想问一下，你这个程序是要怎么样处理？？？因为现目前就只有一个配置，然是我不知道是否需要我将你的代码放到spark程序去进行编译，还是在就当前这个程序进行编译之后将jar放到spark内部？？？

**Comment by fishjoy** [comment]
1. 不需要放到spark程序里面编译，这个是一个独立的工程，虽然代码很少。你可以直接clone下来编译成一个jar包。
2. 使用方式，跟spark依赖别的三方包一样，用spark-submit命令连同你的程序一起提交到spark/spark集群

**Comment by listenLearning** [comment]
我看你的这个是alluxio1.1.0的，然后我现在用的是1.5.0，然后本来我是想修改pom文件的，结果发现不管怎么样，始终都会缺少很多包，那如果我直接使用你这文件的话，会不会出现版本的问题呢

**Comment by fishjoy** [comment]
alluxio1.5我不确定能不能使用，你可以尝试修改一下pom。
另外，你说的缺少很多包？指的是编译过程中缺少alluxio的依赖么？

**Comment by listenLearning** [comment]
对，如果我修改pom之后，会缺少import alluxio.client.ClientContext
import alluxio.client.file.{FileOutStream, FileSystem}
import alluxio.client.file.FileSystem.Factory
import alluxio.client.file.options.{CreateDirectoryOptions, DeleteOptions}这些包，
然后这是我修改后的pom
<dependency>
            <groupId>org.alluxio</groupId>
            <artifactId>alluxio-core-client-fs</artifactId>
            <version>1.5.0</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.alluxio</groupId>
            <artifactId>alluxio-core-client</artifactId>
            <version>1.5.0</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.alluxio</groupId>
            <artifactId>alluxio-core-common</artifactId>
            <version>1.5.0</version>
        </dependency>

**Comment by fishjoy** [comment]
这样的话，应该是alluxio1.5的client接口变了，还需要修改对应的代码。

**Comment by listenLearning** [comment]
我也是这样想的，问题是我们公司现在各种监控，打不开官网了。。。。

**Comment by listenLearning** [comment]
你之前说的是用--jars这种方式对吧？？？我用spark-shell --jars ../lib/spark-alluxio-blockstore.jar 这样方式，但是在执行action操作的时候却说classnotfound，这个是为什么？？我打包的时候已经指定了

**Comment by listenLearning** [comment]
17/08/09 11:28:52 ERROR storage.ExternalBlockStore: Cannot initialize external block store
java.lang.ClassNotFoundException: org.apache.spark.storage.AlluxioBlockManager
        at org.apache.spark.repl.ExecutorClassLoader.findClass(ExecutorClassLoader.scala:88)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:175)
        at org.apache.spark.storage.ExternalBlockStore.createBlkManager(ExternalBlockStore.scala:186)
        at org.apache.spark.storage.ExternalBlockStore.externalBlockManager$lzycompute(ExternalBlockStore.scala:36)
        at org.apache.spark.storage.ExternalBlockStore.externalBlockManager(ExternalBlockStore.scala:36)
        at org.apache.spark.storage.ExternalBlockStore.putIntoExternalBlockStore(ExternalBlockStore.scala:78)
        at org.apache.spark.storage.ExternalBlockStore.putIterator(ExternalBlockStore.scala:67)
        at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:838)
        at org.apache.spark.storage.BlockManager.putIterator(BlockManager.scala:685)
        at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:153)
        at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:78)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
